### ISSUE TITLE
Provide raw data dumps?

### ISSUE THREAD

**Issue by sigpwned** [wooorm/iso-639-2#8]
This project is great! I have contemplated building this myself, and am thrilled to find someone got to it first. Thank you!

However, I'm not using JavaScript. Of course, it's very easy to grab the data from the .js files, but it would be nice if there were raw JSON/CSV/etc. dumps so I didn't have to.

The dump files would be larger, so it would be totally understandable if you didn't want to put them into the code repo itself, but you could also add them to the individual releases as assets if you preferred.

Again, thank you for this wonderful project!

**Comment by wooorm** [comment]
Hey! The data dump is available from loc.gov: https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt.
That’s waht I crawl, like this: https://github.com/wooorm/iso-639-2/blob/main/build.js.
I would like to publish JSON again, but that currently isn’t possible while the JS ecosystem is switching to ESM, which doesn’t have that yet.
For CSV, well, that’s basically the data dump already.
And turning that dump into any other format you like, shouldn’t be too hard!

Sooo, no, I’m not currently interested in providing other formats and maintaining that, sorry!

I’d also recommend going with 639-3 if you can, or a BCP-47 “normalized”/“minimalized” version (like this: https://github.com/wooorm/bcp-47-normalize).

**Comment by sigpwned** [comment]
That is a perfectly valid response, particularly because the data is already available in machine-readable format elsewhere! It might be worth mentioning that link in the README if you find yourself getting this question a lot. And thank you for the link to your other projects! Super useful!
